fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "4.24.0"
    mysql:
      repo: "https://github.com/puppetlabs/puppetlabs-mysql.git"
      ref: "5.1.0"
    postgresql:
      repo: "https://github.com/puppetlabs/puppetlabs-postgresql.git"
      ref: "5.4.0"
    concat:
      repo: "https://github.com/puppetlabs/puppetlabs-concat.git"
      ref: "4.2.1"
    apt:
      repo: "https://github.com/puppetlabs/puppetlabs-apt.git"
      ref: "4.5.1"
    epel:
      repo: "https://github.com/stahnma/puppet-module-epel.git"
      ref: "1.3.0"
  symlinks:
    powerdns: "#{source_dir}"
