fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "5.2.0"
    mysql:
      repo: "https://github.com/puppetlabs/puppetlabs-mysql.git"
      ref: "8.0.0"
    postgresql:
      repo: "https://github.com/puppetlabs/puppetlabs-postgresql.git"
      ref: "5.12.1"
    concat:
      repo: "https://github.com/puppetlabs/puppetlabs-concat.git"
      ref: "5.3.0"
    apt:
      repo: "https://github.com/puppetlabs/puppetlabs-apt.git"
      ref: "6.3.0"
    epel:
      repo: "https://github.com/stahnma/puppet-module-epel.git"
      ref: "2.0.0"
    yumrepo:
      repo: "https://github.com/puppetlabs/puppetlabs-yumrepo_core.git"
      puppet_version: ">= 6.0.0"
      ref: "1.0.3"
    augeas:
      repo: "https://github.com/puppetlabs/puppetlabs-augeas_core.git"
      puppet_version: ">= 6.0.0"
      ref: "1.0.4"
  symlinks:
    powerdns: "#{source_dir}"
